import Image from "next/image";
import Link from "next/link";
import { AddToQuoteButton } from "../../components/add-to-quote-button";
import { ScrollReveal } from "../../components/scroll-reveal";
import heroImg from "../../../assets/images/hooklift_bins.jpg";
import rollOnOff from "../../../assets/images/downwaste_roll_on-off_containers.jpg";
import rollOnOffGreen from "../../../assets/images/downwaste_roll_on-off_containers_green.jpg";
import compactorContainer from "../../../assets/images/downwaste_compactor_container.jpg";
import rubble1 from "../../../assets/images/downwaste_rubble_containers-1.jpg";
import rubble2 from "../../../assets/images/downwaste_rubble_containers-2.jpg";
import openTop1 from "../../../assets/images/downwaste_open_top_containers-1.jpg";
import openTop2 from "../../../assets/images/downwaste_open_top_containers-2.jpg";
import tailored from "../../../assets/images/downwaste_tailored_containers.jpg";
import tailoredSingle from "../../../assets/images/downwaste_tailored_container.jpg";

export const metadata = {
  title: "Hooklift Bins | Downwaste UK",
  description:
    "Roll on/off containers, compactor containers, rubble bins and tailored hooklift solutions for UK construction, commercial and industrial sites. Compatible with all standard hook-lift lorry fleets.",
};

const rollOnOffSpecs = [
  { model: "C-OT-10", volume: "10.0 m³", dimensions: "4,500 × 2,300 × 1,000 mm", weight: "1,458 kg" },
  { model: "C-OT-12", volume: "12.0 m³", dimensions: "5,250 × 2,300 × 1,000 mm", weight: "1,620 kg" },
  { model: "C-OT-18", volume: "18.0 m³", dimensions: "5,250 × 2,300 × 1,500 mm", weight: "1,860 kg" },
  { model: "C-OT-20", volume: "20.7 m³", dimensions: "6,000 × 2,300 × 1,500 mm", weight: "2,040 kg" },
  { model: "C-OT-24", volume: "24.0 m³", dimensions: "6,000 × 2,300 × 1,750 mm", weight: "2,140 kg" },
  { model: "C-OT-31", volume: "31.0 m³", dimensions: "6,000 × 2,300 × 2,250 mm", weight: "2,450 kg" },
];

const rubbleSpecs = [
  { model: "C-TOR-1", volume: "6.5 m³", dimensions: "4,500 × 1,900 × 750 mm", weight: "1,350 kg" },
  { model: "C-TOR-2", volume: "7.1 m³", dimensions: "5,000 × 1,900 × 750 mm", weight: "1,450 kg" },
  { model: "C-TOR-3", volume: "7.8 m³", dimensions: "5,500 × 1,900 × 750 mm", weight: "1,550 kg" },
];

const variants = [
  {
    id: "roll-on-off",
    label: "Roll On/Off Containers",
    body: "Open-top hooklift containers for general mixed waste, bulky waste and recyclables. Six capacity options from 10 to 31 m³ cover everything from a single trade unit to a large logistics compound — all compatible with standard UK hook-lift lorry fleets.",
    images: [rollOnOff, rollOnOffGreen],
    specs: rollOnOffSpecs,
    specNote: "Standard 2,300 mm width — fits within standard UK road transport limits without abnormal load permits.",
  },
  {
    id: "compactor-container",
    label: "Compactor Containers",
    body: "Designed for direct coupling to static or mobile compaction units, these sealed containers accept pre-compacted waste and are built to withstand the forces involved. The leakproof construction satisfies UK waste duty-of-care requirements for liquid-bearing loads.",
    images: [compactorContainer],
    specs: null,
    specNote: "Available in bespoke capacities and coupling configurations — contact our team for M&E coordination drawings.",
  },
  {
    id: "rubble-containers",
    label: "Rubble Containers",
    body: "Reinforced low-sided containers engineered for construction and demolition waste — hardcore, masonry, broken concrete and aggregates. The robust base plate and full-height corner posts handle the high point loads generated by grab lorries and excavator buckets.",
    images: [rubble1, rubble2],
    specs: rubbleSpecs,
    specNote: "Reinforced base and side panels rated for dense aggregate loads. Suitable for principal contractor waste programmes on UK demolition and groundworks contracts.",
  },
  {
    id: "open-top",
    label: "Gravel Containers",
    body: "Heavy-duty open-top containers for bulk aggregate, gravel, sand and loose granular materials. The low drop-side access and stackable design make site logistics straightforward for groundworkers and civil engineering contractors.",
    images: [openTop1, openTop2],
    specs: null,
    specNote: "Full-perimeter base skids for stability when loaded. Fork-pocket compatible for yard storage.",
  },
  {
    id: "tailored",
    label: "Tailored Containers",
    body: "Bespoke hooklift containers designed and fabricated to your exact project requirements — custom dimensions, hydraulic rear doors, colour-coded lids, logo livery, or integrated locking mechanisms for secure waste streams. Frequently specified by principal contractors and FM operators managing complex mixed-use developments.",
    images: [tailored, tailoredSingle],
    specs: null,
    specNote: "CAD drawings and BIM objects available on request. Lead time from confirmed order typically 6–8 weeks.",
  },
];

const features = [
  {
    title: "Hook-lift lorry compatible",
    body: "All containers are designed to EN 1501 hooklift geometry, compatible with every major UK hook-lift fleet — no bespoke vehicles required.",
  },
  {
    title: "Waste duty-of-care ready",
    body: "Leakproof base options and sealed lids support compliance with the Environmental Protection Act 1990 and waste duty-of-care regulations applicable to UK businesses.",
  },
  {
    title: "Hot-dip galvanised option",
    body: "Available with hot-dip galvanised finish for extended outdoor service life — ideal for coastal and high-rainfall UK environments.",
  },
  {
    title: "RAL colour & livery",
    body: "Any RAL colour, company logo or waste-stream colour-coding can be applied at the factory — simplifying waste segregation compliance on managed sites.",
  },
  {
    title: "Stackable design",
    body: "All open-top variants can be stacked when empty, minimising yard footprint on constrained UK construction sites and waste transfer stations.",
  },
  {
    title: "Bespoke fabrication",
    body: "Non-standard dimensions, hydraulic doors, locking mechanisms and integrated compactor couplings available — supporting M&E coordination from RIBA Stage 3 onwards.",
  },
];

const faqs = [
  {
    q: "Are Downwaste hooklift bins compatible with UK hook-lift lorry fleets?",
    a: "Yes. All containers are manufactured to standard EN 1501 hooklift geometry, making them compatible with the Multilift, Hiab, Palfinger and other hook-lift systems operated by UK waste contractors and skip hire firms.",
  },
  {
    q: "What is the maximum payload for the rubble containers?",
    a: "The C-TOR range is engineered for dense construction and demolition waste. Structural calculations are available on request for principal contractor submittals. Always check the gross vehicle weight of the collecting lorry against the load.",
  },
  {
    q: "Can containers be specified with a lock for secure waste streams?",
    a: "Yes. Integrated padlock bars and hasp-and-staple systems can be fabricated onto any container. This is commonly specified for confidential document destruction, electrical waste (WEEE) and pharmaceutical waste streams.",
  },
  {
    q: "What is the lead time for tailored containers?",
    a: "Standard roll on/off and rubble containers are available ex-stock or on short lead times. Tailored and bespoke containers are typically 6–8 weeks from confirmed order and approved drawings.",
  },
  {
    q: "Can we get BIM objects or CAD drawings for M&E coordination?",
    a: "Yes. 2D CAD drawings and IFC/BIM objects are available for all standard container types. Contact our UK technical team with your project reference and programme dates.",
  },
];

export default function HookliftBinsPage() {
  return (
    <div className="text-slate-900">
      {/* Breadcrumb */}
      <div className="border-b border-slate-200 bg-slate-50 px-4 py-3 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-7xl">
          <nav className="flex items-center gap-2 text-xs font-medium text-slate-500">
            <Link href="/" className="hover:text-sky-700 transition-colors">Home</Link>
            <span>/</span>
            <Link href="/products" className="hover:text-sky-700 transition-colors">Products</Link>
            <span>/</span>
            <Link href="/products#containers" className="hover:text-sky-700 transition-colors">Containers</Link>
            <span>/</span>
            <span className="text-slate-800">Hooklift Bins</span>
          </nav>
        </div>
      </div>

      {/* Hero */}
      <div className="bg-gradient-to-br from-slate-950 to-blue-900 px-4 py-14 sm:px-6 sm:py-20 lg:px-8">
        <div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2 lg:items-center">
          <ScrollReveal>
            <p className="text-sm font-semibold uppercase tracking-[0.25em] text-sky-400">
              Containers · Hook-lift Range
            </p>
            <h1 className="mt-2 text-3xl font-bold text-white sm:text-4xl lg:text-5xl">
              Hooklift Bins
            </h1>
            <p className="mt-4 max-w-xl text-base leading-7 text-slate-300 sm:text-lg">
              Roll on/off containers, compactor containers, rubble bins, gravel containers and bespoke fabrications — all built to UK hook-lift lorry geometry. Specified by principal contractors, FM operators and waste managers across the UK.
            </p>
            <div className="mt-6 flex flex-wrap items-center gap-3">
              <AddToQuoteButton id="hooklift-bins" name="Hooklift Bins" category="Containers" size="md" />
              <a
                href="mailto:info@downwaste.com?subject=Hooklift Bins Enquiry"
                className="inline-flex items-center gap-2 rounded-full border border-slate-600 px-6 py-2.5 text-sm font-bold text-slate-300 transition-all hover:border-sky-400 hover:text-sky-400"
              >
                Speak to the team
              </a>
            </div>
          </ScrollReveal>

          <ScrollReveal variant="scale">
            <Image
              src={heroImg}
              alt="Downwaste hooklift bins — row of compactor containers in a UK distribution warehouse"
              className="rounded-2xl shadow-2xl"
              sizes="(max-width: 1024px) 100vw, 50vw"
              priority
            />
          </ScrollReveal>
        </div>
      </div>

      {/* Jump-links */}
      <div className="sticky top-[57px] sm:top-[73px] z-20 border-b border-slate-200 bg-white/95 backdrop-blur-sm">
        <div className="mx-auto max-w-7xl overflow-x-auto px-4 sm:px-6 lg:px-8">
          <nav className="flex gap-1 py-2" aria-label="Hooklift bin types">
            {variants.map((v) => (
              <a
                key={v.id}
                href={`#${v.id}`}
                className="shrink-0 rounded-full px-3 py-1.5 text-xs font-semibold text-slate-600 transition-colors hover:bg-sky-50 hover:text-sky-700"
              >
                {v.label}
              </a>
            ))}
          </nav>
        </div>
      </div>

      {/* Variant sections */}
      {variants.map((v, vi) => (
        <section
          key={v.id}
          id={v.id}
          className={`px-4 py-14 sm:px-6 sm:py-20 lg:px-8 scroll-mt-[117px] sm:scroll-mt-[133px] ${vi % 2 === 0 ? "bg-white" : "bg-slate-50"}`}
        >
          <div className="mx-auto max-w-7xl">
            <div className={`grid gap-10 lg:grid-cols-2 lg:items-start ${vi % 2 !== 0 ? "lg:[&>*:first-child]:order-2" : ""}`}>
              {/* Text + specs */}
              <ScrollReveal>
                <p className="text-sm font-semibold uppercase tracking-widest text-sky-600">
                  {String(vi + 1).padStart(2, "0")}
                </p>
                <h2 className="mt-1 text-2xl font-bold text-slate-950 sm:text-3xl">{v.label}</h2>
                <p className="mt-3 text-base leading-7 text-slate-600">{v.body}</p>
                {v.specNote && (
                  <p className="mt-3 rounded-xl border border-sky-200 bg-sky-50 px-4 py-3 text-xs font-medium text-sky-800">
                    {v.specNote}
                  </p>
                )}

                {v.specs && (
                  <div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 shadow-sm">
                    <table className="w-full min-w-[480px] text-sm">
                      <thead className="bg-gradient-to-r from-slate-950 to-blue-900 text-white">
                        <tr>
                          {["Model", "Volume", "L × W × H", "Weight"].map((h) => (
                            <th key={h} className="px-4 py-3 text-left text-xs font-bold uppercase tracking-wider">{h}</th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {v.specs.map((s, i) => (
                          <tr key={s.model} className={i % 2 === 0 ? "bg-white" : "bg-slate-50"}>
                            <td className="px-4 py-2.5 font-bold text-slate-950">{s.model}</td>
                            <td className="px-4 py-2.5 font-semibold text-sky-700">{s.volume}</td>
                            <td className="px-4 py-2.5 text-slate-600">{s.dimensions}</td>
                            <td className="px-4 py-2.5 text-slate-600">{s.weight}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}

                <div className="mt-6">
                  <AddToQuoteButton id={`hooklift-${v.id}`} name={`Hooklift Bin — ${v.label}`} category="Containers" size="sm" />
                </div>
              </ScrollReveal>

              {/* Images */}
              <ScrollReveal variant="scale" className="grid gap-4">
                {v.images.map((img, i) => (
                  <Image
                    key={i}
                    src={img}
                    alt={`${v.label} — Downwaste UK`}
                    className="w-full rounded-2xl shadow-md"
                    sizes="(max-width: 1024px) 100vw, 50vw"
                  />
                ))}
              </ScrollReveal>
            </div>
          </div>
        </section>
      ))}

      {/* Features */}
      <div className="bg-gradient-to-br from-slate-950 to-blue-900 px-4 py-14 sm:px-6 sm:py-20 lg:px-8">
        <div className="mx-auto max-w-7xl">
          <ScrollReveal>
            <p className="text-sm font-semibold uppercase tracking-widest text-sky-400">Key Features</p>
            <h2 className="mt-2 text-2xl font-bold text-white sm:text-3xl">Built for UK compliance &amp; operations</h2>
          </ScrollReveal>
          <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((f, i) => (
              <ScrollReveal key={f.title} delay={i * 70}>
                <div className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur-sm">
                  <h3 className="font-bold text-white">{f.title}</h3>
                  <p className="mt-2 text-sm leading-6 text-slate-300">{f.body}</p>
                </div>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </div>

      {/* FAQs */}
      <div className="bg-slate-50 px-4 py-14 sm:px-6 sm:py-20 lg:px-8">
        <div className="mx-auto max-w-3xl">
          <ScrollReveal>
            <p className="text-sm font-semibold uppercase tracking-widest text-sky-600">FAQs</p>
            <h2 className="mt-2 text-2xl font-bold text-slate-950 sm:text-3xl">Common questions</h2>
          </ScrollReveal>
          <div className="mt-8 space-y-4">
            {faqs.map((faq, i) => (
              <ScrollReveal key={i} delay={i * 60}>
                <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
                  <h3 className="font-bold text-slate-950">{faq.q}</h3>
                  <p className="mt-2 text-sm leading-6 text-slate-600">{faq.a}</p>
                </div>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </div>

      {/* CTA */}
      <div className="bg-white px-4 py-16 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl text-center">
          <ScrollReveal>
            <h2 className="text-2xl font-bold text-slate-950 sm:text-3xl">
              Ready to specify hooklift containers?
            </h2>
            <p className="mt-4 text-slate-600">
              Add to your quote, or contact our UK technical team for CAD drawings, BIM objects and programme coordination with your principal contractor or waste management partner.
            </p>
            <div className="mt-8 flex flex-wrap justify-center gap-4">
              <AddToQuoteButton id="hooklift-bins" name="Hooklift Bins" category="Containers" size="md" />
              <Link
                href="/quote"
                className="inline-flex items-center gap-2 rounded-full border border-slate-300 px-6 py-2.5 text-sm font-bold text-slate-700 transition-all hover:border-sky-400 hover:text-sky-700"
              >
                View my quote
              </Link>
            </div>
          </ScrollReveal>
        </div>
      </div>
    </div>
  );
}
